.SUFFIXES : .cs

.cs.exe:
	csc $<


all: class_generics.exe class.exe constructors.exe inheritance.exe nested.exe overload.exe polymorphism.exe private.exe staticmethod.exe this.exe

clean:
	del *.exe
